install accuknox agents using the operator
accuknox/agents-operator pull request #11
Opened 2023-01-05 13:10 UTC by Ankurk99

Install accuknox-agents (shared-informer, policy-enforcement-agent, feeder-service, discover-engine) using the operator if deployment is not running.

2023-01-05 13:10 UTC, Ankurk99 commented
Draft because handling the env variables to be passed with these agents.

2023-01-06 02:15 UTC, nyrahul requested changes

2023-01-06 02:15 UTC, nyrahul commented on cmd/agents-operator/main.go
> +			} `yaml:"env"`
This need not be on per agent basis.

2023-01-06 02:15 UTC, nyrahul commented on cmd/agents-operator/main.go
>  			log.Error().Msg(err.Error())
```suggestion
			log.Error().Msgf("Resource not updated: %s err=%v", resource.Name, err)
```

2023-01-06 02:15 UTC, nyrahul commented on cmd/agents-operator/main.go
> +		log.Error().Msgf("Error locating chart: %v", err)
return

2023-01-06 02:15 UTC, nyrahul commented on cmd/agents-operator/main.go
> +		log.Error().Msgf("Error loading chart: %v", err)
return

2023-01-06 02:15 UTC, nyrahul commented on cmd/agents-operator/main.go
> +		log.Error().Msgf("Error in Mergevalues: %v", err.Error())
return

2023-01-06 02:15 UTC, nyrahul commented on cmd/agents-operator/main.go
> +		os.Exit(1)
```suggestion
		return
```

2023-01-06 02:15 UTC, nyrahul commented on cmd/agents-operator/main.go
> +			}
why this code? Keep the chart name in the configmap in the context of the agent.

2023-01-06 02:15 UTC, nyrahul commented on cmd/agents-operator/main.go
> +	repo := "accuknox-agents-dev/"
This should be in the configmap.

2023-01-06 02:15 UTC, nyrahul commented on deployment/deployment.yaml
> +            cluster_id: 0
Why is this kept in the configmap?

2023-01-06 02:15 UTC, nyrahul commented on go.mod
> +	github.com/antonmedv/expr v1.9.0
Why is this dep added newly?

2023-01-06 02:19 UTC, nyrahul requested changes

2023-01-06 02:19 UTC, nyrahul commented on cmd/agents-operator/main.go
> +		"set":    "serviceAccount.Namespace=accuknox-agents",
`accuknox-agents` should not be hardcoded. We have `globalns` that has the namespace name.

2023-01-06 02:19 UTC, nyrahul commented on cmd/agents-operator/main.go
> +func installAgents(cfg *action.Configuration, settings *cli.EnvSettings, data AgentConfig, i int, name, chartRef, ns string) {
Lets not use different var names for AgentConfig for different APIs.

2023-01-06 08:08 UTC, Ankurk99 commented on go.mod
> +	github.com/antonmedv/expr v1.9.0
was present in indirect required modules before

2023-01-07 11:31 UTC, nyrahul requested changes

2023-01-07 11:31 UTC, nyrahul commented on Makefile
> +BASE_IMAGE ?= ubuntu:latest
Lets use distroless image. 
download helm bin and copy from your host machine

2023-01-07 11:31 UTC, nyrahul commented on deployment/deployment.yaml
> +  name: cluster-admin
We cannot use `cluster-admin`.

2023-01-07 15:19 UTC, Ankurk99 commented on Makefile
> +BASE_IMAGE ?= ubuntu:latest
As discussed on slack, this will add additional issues with respect to copying helm and sh binaries

2023-01-07 15:20 UTC, Ankurk99 commented on deployment/deployment.yaml
> +  name: cluster-admin
Will be handled separately in #13

2023-01-09 04:20 UTC, nyrahul approved these changes

2023-01-09 04:20 UTC, merged